# utils/eventos.py
"""
Constantes de eventos para CDatalog.
Usar siempre estos valores para evitar errores de tipeo.
"""

class Eventos:
    """Eventos de Configuración"""
    CONFIG              = "Configurac"
    CFG_NUEVO_DIA       = "Nuevo Dia "
    CFG_REENCENDIDO     = "Reencendid"
    CFG_ENCENDIDO       = "Encendido "
    CBIO_CARGA          = "Cbio Carga"
    RECH_CARGA          = "Rech Carga"
    CBIO_DOSIS          = "Cbio Dosis"
    RECH_DOSIS          = "Rech Dosis"
    CBIO_QBOMBA         = "Cbio QBomb"
    RECH_QBOMBA         = "Rech QBomb"
    CBIO_ENCENDIDO      = "Cbio EncBo"
    RECH_ENCENDIDO      = "Rech EncBo"
    CBIO_DESCANSO       = "Cbio DesBo"
    RECH_DESCANSO       = "Rech DesBo"
    CBIO_PORCENTAJE     = "Cbio %Cont"
    RECH_PORCENTAJE     = "Rech %Cont"
    CBIO_QBEBIDA        = "Cbio QBebi"
    RECH_QBEBIDA        = "Rech QBebi"
    CBIO_AGUA_CONSUMIDA = "Cbio ACons"
    RECH_AGUA_CONSUMIDA = "Rech ACons"

    """Eventos de Operación"""
    ESTADO_FIN_DIA      = "Est FinDia"
    VB_ABRE             = "VB Abre   "
    VB_CIERRA           = "VB Cierra "
    BOMBA_ARRANCA       = "BombArranc"
    BOMBA_PARA          = "Bomba Para"
    DOSIS_COMPLETADA    = "DosisCompl"
    BOMBA_ATRASADA      = "BombAtrasa"
    BOMBA_RECUPERADA    = "BombaRecup"
    REENCENDIDO         = "Reencendid"
    ENCENDIDO           = "Encendido "